from importlib.resources import files
from pathlib import Path
import os
from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from uuid import uuid4
import time
import logging
import asyncio
from contextlib import nullcontext

from starlette.staticfiles import StaticFiles

# Load environment variables
load_dotenv()

# Import agents and context creation from main_qwen (SUPPORT QWEN MODEL)
from .main_qwen import (
	triage_agent,
	faq_agent,
	seat_booking_agent,
	flight_status_agent,
	cancellation_agent,
	create_initial_context,
	AirlineAgentContext,
	food_service_agent,
	USE_FOOD_MCP,
	FOOD_MCP_SERVER,
)
from .main_qwen import OpenAIModel as bOpenAIModel  # True: use OpenAI model; False: use Qwen model
from .main_qwen import myRunConfig
from .storage import CompositeConversationStore, JsonConversationStore, PostgresConversationStore
from .telemetry import Telemetry
from .evaluators import evaluate_and_score_trace
from .data_loader import get_seats_by_flight
from .seat_assignments import seat_assignment_store


"""
from main import (
    triage_agent,
    faq_agent,
    seat_booking_agent,
    flight_status_agent,
    cancellation_agent,
    create_initial_context,
)
"""

from agents import (
	Runner,
	ItemHelpers,
	MessageOutputItem,
	HandoffOutputItem,
	ToolCallItem,
	ToolCallOutputItem,
	InputGuardrailTripwireTriggered,
	Handoff,
)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Enable OpenInference tracing when available.
try:
	from openinference.instrumentation.openai_agents import OpenAIAgentsInstrumentor
	OpenAIAgentsInstrumentor().instrument()
	OPENINFERENCE_ENABLED = True
except Exception as e:
	logger.info("OpenInference instrumentation unavailable: %s", e)
	OPENINFERENCE_ENABLED = False

#===================================================================================
# Initialize Langfuse client for trace management (v3 API)
#===================================================================================
try:
	from langfuse import get_client
	# Note: get_client() automatically reads from environment variables:
	# LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_HOST (or LANGFUSE_BASE_URL)
	langfuse_client = get_client()
	logger.info("Langfuse client initialized successfully (v3 SDK)")
	LANGFUSE_ENABLED = True
except Exception as e:
	logger.warning(f"Langfuse initialization failed: {e}. Tracing will be disabled.")
	langfuse_client = None
	LANGFUSE_ENABLED = False

#fastapi app instance
app = FastAPI()

# CORS configuration (adjust as needed for deployment)
app.add_middleware(
	CORSMiddleware,
	allow_origins=[
		"http://localhost:3000",
		"http://127.0.0.1:3000",
		"http://localhost:3001",
		"http://127.0.0.1:3001",
		"http://localhost:3002",
		"http://127.0.0.1:3002",
	],

	allow_credentials=True,
	allow_methods=["*"],
	allow_headers=["*"],
	expose_headers=["*"],
)


# =========================
# Models
# =========================

# From frontend request
class ChatRequest(BaseModel):
	conversation_id: Optional[str] = None
	message: str

# agent message response
class MessageResponse(BaseModel):
	id: str
	content: str
	agent: str
	trace_id: Optional[str] = None
	timestamp: float
	feedback: Optional[float] = None
	rating: Optional[int] = None
	comment: Optional[str] = None

# agent event log of workflow
class AgentEvent(BaseModel):
	id: str
	type: str
	agent: str
	content: str
	metadata: Optional[Dict[str, Any]] = None
	timestamp: Optional[float] = None

# guardrail check input/output
class GuardrailCheck(BaseModel):
	id: str
	name: str
	input: str
	reasoning: str
	passed: bool
	timestamp: float


class FeedbackRequest(BaseModel):
	conversation_id: str
	message_id: str
	trace_id: str
	score: Optional[float] = None
	rating: Optional[int] = None
	comment: Optional[str] = None


class SeatMapSection(BaseModel):
	rows: List[int] = Field(default_factory=list)
	seats_per_row: List[str] = Field(default_factory=list)
	occupied: List[str] = Field(default_factory=list)
	exit_rows: List[int] = Field(default_factory=list)
	premium: List[str] = Field(default_factory=list)


class SeatMapResponse(BaseModel):
	conversation_id: str
	flight_number: str
	aircraft: Optional[str] = None
	sections: Dict[str, SeatMapSection]
	current_seat: Optional[str] = None

#****************************************************************************************************
# ===================================================================================================
# Response Model： sending response back to frontend app
# Add fields, such as trace id for getting user feedback from frontend, fastapi app sending trace id
# generated by tracing agent run with langfuse， to frontend for display message with trace ID. 
# Traces can be scored in frontend app if obersavation platform allows multiple accesses simultaneously. 
# Otherwise，they can be sent back along with feedback values to backend for computing scores.
# ===================================================================================================
#****************************************************************************************************
class ChatResponse(BaseModel):
	conversation_id: str
	current_agent: str
	messages: List[MessageResponse]
	events: List[AgentEvent]
	context: Dict[str, Any]
	agents: List[Dict[str, Any]]
	guardrails: List[GuardrailCheck] = Field(default_factory=list)
	trace_id: Optional[str] = None

#===================================================================================
# Persistent conversation store instance
#===================================================================================
data_dir = Path(__file__).resolve().parent / "data"
primary_store = None
try:
	primary_store = PostgresConversationStore(
		context_loader=lambda payload: AirlineAgentContext(**payload),
		seed_path=data_dir / "conversations.json",
	)
except Exception as exc:
	logger.warning("Postgres store unavailable, using JSON store only: %s", exc)

json_store = JsonConversationStore(
	data_dir / "conversations.json",
	context_loader=lambda payload: AirlineAgentContext(**payload),
)

if primary_store is None:
	conversation_store = json_store
else:
	conversation_store = CompositeConversationStore(
		primary_store,
		json_store,
		sync_secondary_from_primary=True,
	)

#===================================================================================
# Telemetry for trace logging and feedback forwarding
#===================================================================================
telemetry = Telemetry(
	trace_log=data_dir / "traces.jsonl",
	feedback_log=data_dir / "feedback.jsonl",
)


@app.on_event("startup")
async def _connect_food_mcp() -> None:
	"""Ensure the Food MCP server is connected before handling requests."""
	if USE_FOOD_MCP and FOOD_MCP_SERVER is not None:
		try:
			await FOOD_MCP_SERVER.connect()
			logger.info("Food MCP server connected")
		except Exception as exc:
			logger.warning("Failed to connect Food MCP server: %s", exc)

# =========================
# Helpers
# =========================

def _get_agent_by_name(name: str):
	"""Return the agent object by name."""
	agents = {
		triage_agent.name: triage_agent,
		faq_agent.name: faq_agent,
		seat_booking_agent.name: seat_booking_agent,
		flight_status_agent.name: flight_status_agent,
		cancellation_agent.name: cancellation_agent,
		food_service_agent.name: food_service_agent,
	}
	return agents.get(name, triage_agent)

def _get_guardrail_name(g) -> str:
	"""Extract a friendly guardrail name."""
	name_attr = getattr(g, "name", None)
	if isinstance(name_attr, str) and name_attr:
		return name_attr
	guard_fn = getattr(g, "guardrail_function", None)
	if guard_fn is not None and hasattr(guard_fn, "__name__"):
		return guard_fn.__name__.replace("_", " ").title()
	fn_name = getattr(g, "__name__", None)
	if isinstance(fn_name, str) and fn_name:
		return fn_name.replace("_", " ").title()
	return str(g)

def _build_agents_list() -> List[Dict[str, Any]]:
	"""Build a list of all available agents and their metadata."""
	def make_agent_dict(agent):
		return {
			"name": agent.name,
			"description": getattr(agent, "handoff_description", ""),
			"handoffs": [getattr(h, "agent_name", getattr(h, "name", "")) for h in getattr(agent, "handoffs", [])],
			"tools": [getattr(t, "name", getattr(t, "__name__", "")) for t in getattr(agent, "tools", [])],
			"input_guardrails": [_get_guardrail_name(g) for g in getattr(agent, "input_guardrails", [])],
		}
	return [
		make_agent_dict(triage_agent),
		make_agent_dict(faq_agent),
		make_agent_dict(seat_booking_agent),
		make_agent_dict(flight_status_agent),
		make_agent_dict(cancellation_agent),
		make_agent_dict(food_service_agent),
	]

def _extract_langfuse_trace_id(trace_obj: Any) -> Optional[str]:
	"""Best-effort extract Langfuse trace id from a trace/span object."""
	if trace_obj is None:
		return None
	for attr in ("trace_id", "id"):
		value = getattr(trace_obj, attr, None)
		if isinstance(value, str) and value:
			return value
	return None

def _start_otel_span(name: str):
	"""Start an OpenTelemetry span when tracing is available."""
	try:
		from opentelemetry import trace as otel_trace
	except Exception:
		return nullcontext()

	tracer = otel_trace.get_tracer(__name__)
	return tracer.start_as_current_span(name)

def _trace_id_from_span(span: Any) -> Optional[str]:
	"""Extract the trace id from a span."""
	if span is None:
		return None
	ctx = span.get_span_context()
	if not ctx or not getattr(ctx, "is_valid", False):
		return None
	trace_id = getattr(ctx, "trace_id", None)
	if isinstance(trace_id, int) and trace_id:
		return f"{trace_id:032x}"
	if isinstance(trace_id, str) and trace_id:
		return trace_id
	return None

# =========================
# Background Tasks
# =========================

async def run_llm_judge_evaluation(
	trace_id: str,
	user_message: str,
	assistant_messages: List[str],
	agent_name: str,
):
	"""Background task to evaluate response quality using LLM-as-a-Judge."""
	if not LANGFUSE_ENABLED or not langfuse_client:
		logger.info("Langfuse not enabled, skipping LLM judge evaluation")
		return

	try:
		await evaluate_and_score_trace(
			trace_id=trace_id,
			user_message=user_message,
			assistant_messages=assistant_messages,
			agent_name=agent_name,
			langfuse_client=langfuse_client,
		)
		logger.info(f"LLM judge evaluation completed for trace {trace_id}")
	except Exception as e:
		logger.error(f"LLM judge evaluation failed for trace {trace_id}: {e}")


# =========================
# Main Chat Endpoint
# =========================

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest, background_tasks: BackgroundTasks):
	print(f"Received chat request: conversation_id={req.conversation_id}, message={req.message} ")
	trace_id = uuid4().hex
	external_trace_id = trace_id
	now_ms = time.time() * 1000
	langfuse_trace = None

	"""
	Main chat endpoint for agent orchestration.
	Handles conversation state, agent routing, and guardrail checks.
	"""
	# Initialize or retrieve conversation state
	existing_state = conversation_store.get(req.conversation_id) if req.conversation_id else None
	is_new = existing_state is None
	if is_new:
		conversation_id: str = uuid4().hex
		ctx = create_initial_context()   #flight booking context
		if hasattr(ctx, "conversation_id"):
			ctx.conversation_id = conversation_id
		current_agent_name = triage_agent.name

		#========================================
		#     state for first time conversation
		#========================================
		state: Dict[str, Any] = {
			"input_items": [], #list of TResponseInputItem for Runner.run
			"context": ctx,   #flight booking context
			"current_agent": current_agent_name, #agent to start with
			"trace_history": [],
			"feedback": [],
		}
		if req.message.strip() == "":
			conversation_store.save(conversation_id, state)
			return ChatResponse(
				conversation_id=conversation_id,
				current_agent=current_agent_name,
				messages=[],
				events=[],
				context=ctx.model_dump(),
				agents=_build_agents_list(),
				guardrails=[],
				trace_id=trace_id,
			)
	else:
		conversation_id = req.conversation_id
		#===============================================
		#   retrieve state for conversation from store
		#===============================================
		if existing_state is None:
			raise HTTPException(status_code=404, detail="Conversation not found")
		state = existing_state
		ctx = state.get("context")
		if hasattr(ctx, "conversation_id") and not getattr(ctx, "conversation_id", None):
			ctx.conversation_id = conversation_id
		elif isinstance(ctx, dict):
			ctx.setdefault("conversation_id", conversation_id)

	#=============================================
	# prepare parameters for Runner
	#=============================================
	current_agent = _get_agent_by_name(state["current_agent"])  #pick this agent for running
	state["input_items"].append({"content": req.message, "role": "user"})   #input for runner.run
	old_context = state["context"].model_dump().copy() if hasattr(state["context"], "model_dump") else dict(state["context"])  #context for runner.run
	guardrail_checks: List[GuardrailCheck] = []
	otel_trace_id = None

	try:
		result = None

		with _start_otel_span("agent_chat_interaction") as otel_span:
			otel_trace_id = _trace_id_from_span(otel_span)
			if otel_trace_id:
				trace_id = otel_trace_id
			if otel_span:
				otel_span.set_attribute("input", req.message)
				otel_span.set_attribute("conversation_id", conversation_id)
				otel_span.set_attribute("user_id", conversation_id or "anonymous")

			#===========================================================================================
			# check: https://openai.github.io/openai-agents-python/ref/run/#agents.run.Runner.run
			# run with input(list[TResponseInputItem] ) and context (flight booking context)
			#===========================================================================================
			if(bOpenAIModel): #zdjiang added for qwen3
				result = await Runner.run(current_agent, state["input_items"], context=state["context"])
			else:
				result = await Runner.run(current_agent, state["input_items"], context=state["context"], run_config=myRunConfig)
			if otel_span:
				try:
					output_preview = [
						ItemHelpers.text_message_output(item)
						for item in result.new_items
						if isinstance(item, MessageOutputItem)
					]
					if output_preview:
						otel_span.set_attribute("output", output_preview)
				except Exception:
					pass

	except InputGuardrailTripwireTriggered as e: #gurdrail tripwire triggered
		failed = e.guardrail_result.guardrail
		gr_output = e.guardrail_result.output.output_info
		gr_reasoning = getattr(gr_output, "reasoning", "")
		gr_input = req.message
		gr_timestamp = time.time() * 1000
		for g in current_agent.input_guardrails:
			guardrail_checks.append(GuardrailCheck(
				id=uuid4().hex,
				name=_get_guardrail_name(g),
				input=gr_input,
				reasoning=(gr_reasoning if g == failed else ""),
				passed=(g != failed),
				timestamp=gr_timestamp,
			))
		refusal = "Sorry, I can only answer questions related to airline travel."
		state["input_items"].append({"role": "assistant", "content": refusal})  # record refusal in conversation history
		refusal_message = MessageResponse(
			id=uuid4().hex,
			content=refusal,
			agent=current_agent.name,
			trace_id=trace_id,
			timestamp=gr_timestamp,
		)
		conversation_store.save(conversation_id, state)
		telemetry.record_trace(
			trace_id=trace_id,
			conversation_id=conversation_id,
			agent=current_agent.name,
			user_message=req.message,
			assistant_messages=[refusal_message.model_dump()],
			guardrails=[gc.model_dump() for gc in guardrail_checks],
		)
		return ChatResponse(
			conversation_id=conversation_id,
			current_agent=current_agent.name,
			messages=[refusal_message],
			events=[],
			context=state["context"].model_dump() if hasattr(state["context"], "model_dump") else state["context"],
			agents=_build_agents_list(),
			guardrails=guardrail_checks,
			trace_id=trace_id,
		)
    
	# ===============================
	#  Process result items
	#================================
	messages: List[MessageResponse] = []  #agent messages to return
	events: List[AgentEvent] = []  #agent events to return
    
	#================================================================================
	# Process new items from the run result
	# check: https://openai.github.io/openai-agents-python/ref/result/
	# check: https://openai.github.io/openai-agents-python/ref/items/
	#================================================================================
	for item in result.new_items:
		if isinstance(item, MessageOutputItem):
			text = ItemHelpers.text_message_output(item)
			msg_ts = time.time() * 1000
			msg_id = uuid4().hex
			messages.append(
				MessageResponse(
					id=msg_id,
					content=text,
					agent=item.agent.name,
					trace_id=trace_id,
					timestamp=msg_ts,
				)
			)
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="message",
					agent=item.agent.name,
					content=text,
					timestamp=msg_ts,
				)
			)
        
		# Handle handoff output and agent switching
		elif isinstance(item, HandoffOutputItem):
			# Record the handoff event
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="handoff",
					agent=item.source_agent.name,
					content=f"{item.source_agent.name} -> {item.target_agent.name}",
					metadata={"source_agent": item.source_agent.name, "target_agent": item.target_agent.name},
					timestamp=time.time() * 1000,
				)
			)
			# If there is an on_handoff callback defined for this handoff, show it as a tool call
			from_agent = item.source_agent
			to_agent = item.target_agent
			# Find the Handoff object on the source agent matching the target
			ho = next(
				(	h for h in getattr(from_agent, "handoffs", [])
					if isinstance(h, Handoff) and getattr(h, "agent_name", None) == to_agent.name),
				None,
			)
			if ho:
				fn = ho.on_invoke_handoff
				fv = fn.__code__.co_freevars
				cl = fn.__closure__ or []
				if "on_handoff" in fv:
					idx = fv.index("on_handoff")
					if idx < len(cl) and cl[idx].cell_contents:
						cb = cl[idx].cell_contents
						cb_name = getattr(cb, "__name__", repr(cb))
						events.append(
							AgentEvent(
								id=uuid4().hex,
								type="tool_call",
								agent=to_agent.name,
								content=cb_name,
								timestamp=time.time() * 1000,
							)
						)
			#==========================================================
			# handoff target agent is the starting agent of next run
			current_agent = item.target_agent
			#==========================================================

		elif isinstance(item, ToolCallItem):
			tool_name = getattr(item.raw_item, "name", None)
			raw_args = getattr(item.raw_item, "arguments", None)
			tool_args: Any = raw_args
			if isinstance(raw_args, str):
				try:
					import json
					tool_args = json.loads(raw_args)
				except Exception:
					pass
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="tool_call",
					agent=item.agent.name,
					content=tool_name or "",
					metadata={"tool_args": tool_args},
					timestamp=time.time() * 1000,
				)
			)
            
			#================== important trick for frontend interaction ===================================
			# If the tool is display_seat_map, send a special message so the UI can render the seat selector.
			#===============================================================================================
			if tool_name == "display_seat_map":
				messages.append(
					MessageResponse(
						id=uuid4().hex,
						content="DISPLAY_SEAT_MAP",
						agent=item.agent.name,
						trace_id=trace_id,
						timestamp=time.time() * 1000,
					)
				)
		elif isinstance(item, ToolCallOutputItem):
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="tool_output",
					agent=item.agent.name,
					content=str(item.output),
					metadata={"tool_result": item.output},
					timestamp=time.time() * 1000,
				)
			)

	#==================================================================================================
	# Resolve trace id: prefer OpenTelemetry (OpenInference) trace id when available.
	#==================================================================================================
	if otel_trace_id:
		trace_id = otel_trace_id
	else:
		if LANGFUSE_ENABLED and langfuse_client:
			try:
				# Fallback: create Langfuse trace only when no OTel trace is available.
				langfuse_trace = langfuse_client.start_span(
					name="agent_chat_interaction",
					metadata={
						"external_trace_id": external_trace_id,
						"conversation_id": req.conversation_id,
						"user_id": req.conversation_id or "anonymous",
						"user_message": req.message,
						"timestamp": now_ms,
					},
				)
				langfuse_trace_id = _extract_langfuse_trace_id(langfuse_trace)
				if langfuse_trace_id:
					trace_id = langfuse_trace_id
					logger.info(
						"Using Langfuse trace id %s for UI feedback (external=%s)",
						trace_id,
						external_trace_id,
					)
				logger.info(f"Created Langfuse trace: {trace_id}")
			except Exception as e:
				logger.warning(f"Failed to create Langfuse trace: {e}")

	for msg in messages:
		msg.trace_id = trace_id

	# Check for context updates
	new_context = state["context"].model_dump()
	changes = {k: new_context[k] for k in new_context if old_context.get(k) != new_context[k]}
	if changes:
		events.append(
			AgentEvent(
				id=uuid4().hex,
				type="context_update",
				agent=current_agent.name,
				content="",
				metadata={"changes": changes},
				timestamp=time.time() * 1000,
			)
		)
	#==================================================================================================
	# Save updated conversation state
	# https://openai.github.io/openai-agents-python/running_agents/#conversationschat-threads
	# https://openai.github.io/openai-agents-python/ref/result/#agents.result.RunResult.to_input_list
	state["input_items"] = result.to_input_list() #check above links for to_input_list method details
	state["current_agent"] = current_agent.name
	#==================================================================================================

	# Build guardrail results: mark failures (if any), and any others as passed
	final_guardrails: List[GuardrailCheck] = []
	for g in getattr(current_agent, "input_guardrails", []):
		name = _get_guardrail_name(g)
		failed = next((gc for gc in guardrail_checks if gc.name == name), None)
		if failed:
			final_guardrails.append(failed)
		else:
			final_guardrails.append(GuardrailCheck(
				id=uuid4().hex,
				name=name,
				input=req.message,
				reasoning="",
				passed=True,
				timestamp=time.time() * 1000,
			))

	state.setdefault("trace_history", []).append(
		{
			"trace_id": trace_id,
			"timestamp": now_ms,
			"agent": current_agent.name,
			"messages": [m.model_dump() for m in messages],
			"guardrails": [g.model_dump() for g in final_guardrails],
		}
	)
	conversation_store.save(conversation_id, state)

	telemetry.record_trace(
		trace_id=trace_id,
		conversation_id=conversation_id,
		agent=current_agent.name,
		user_message=req.message,
		assistant_messages=[m.model_dump() for m in messages],
		guardrails=[g.model_dump() for g in final_guardrails],
		metadata={"events": [e.model_dump() for e in events]},
	)

	#===================================================================================
	# Update and end Langfuse trace with agent response and metadata (v3 API)
	#===================================================================================
	if LANGFUSE_ENABLED and langfuse_trace:
		try:
			langfuse_trace.update(
				output={"messages": [m.content for m in messages]},
				metadata={
					"agent": current_agent.name,
					"guardrails_passed": all(g.passed for g in final_guardrails),
					"events_count": len(events),
					"context": state["context"].model_dump() if hasattr(state["context"], "model_dump") else state["context"],
				},
			)
			# End the span to complete the trace
			langfuse_trace.end()
			# Flush to ensure data is sent to Langfuse
			langfuse_client.flush()
			logger.info(f"Updated and ended Langfuse trace {trace_id} with agent response")
		except Exception as e:
			logger.warning(f"Failed to update Langfuse trace: {e}")

	#===================================================================================
	# Schedule LLM-as-a-Judge evaluation as background task (optional - can be disabled)
	#===================================================================================
	if messages and os.getenv("ENABLE_LLM_JUDGE", "true").lower() == "true":
		background_tasks.add_task(
			run_llm_judge_evaluation,
			trace_id=trace_id,
			user_message=req.message,
			assistant_messages=[m.content for m in messages],
			agent_name=current_agent.name,
		)
		logger.info(f"Scheduled LLM judge evaluation for trace {trace_id}")

	#return response for frontend
	return ChatResponse(
		conversation_id=conversation_id,
		current_agent=current_agent.name,
		messages=messages,
		events=events,
		context=state["context"].model_dump(),
		agents=_build_agents_list(),
		guardrails=final_guardrails,
		trace_id=trace_id,
	)


@app.post("/api/feedback")
async def feedback_endpoint(req: FeedbackRequest):
	"""Collect user feedback from the UI and optionally forward to Langfuse."""
	if req.score is None and req.rating is None and not (req.comment and req.comment.strip()):
		raise HTTPException(status_code=400, detail="Feedback must include a score, rating, or comment")
	if req.score is not None and (req.score < 0 or req.score > 1):
		raise HTTPException(status_code=400, detail="Score must be between 0 and 1")
	if req.rating is not None and req.rating not in range(1, 6):
		raise HTTPException(status_code=400, detail="Rating must be between 1 and 5")

	comment = req.comment.strip() if req.comment else None

	state = conversation_store.get(req.conversation_id)
	if state is None:
		raise HTTPException(status_code=404, detail="Conversation not found")

	entry = {
		"message_id": req.message_id,
		"trace_id": req.trace_id,
		"score": req.score,
		"rating": req.rating,
		"comment": comment,
		"timestamp": time.time() * 1000,
	}
	state.setdefault("feedback", []).append(entry)
	conversation_store.save(req.conversation_id, state)

	sent_results = []
	if req.score is not None:
		sent_results.append(
			telemetry.submit_feedback(
				trace_id=req.trace_id,
				score=req.score,
				comment=comment,
				metadata={
					"conversation_id": req.conversation_id,
					"message_id": req.message_id,
					"feedback_type": "binary",
				},
				score_name="user-feedback",
			)
		)
	if req.rating is not None:
		sent_results.append(
			telemetry.submit_feedback(
				trace_id=req.trace_id,
				score=float(req.rating),
				comment=comment,
				metadata={
					"conversation_id": req.conversation_id,
					"message_id": req.message_id,
					"feedback_type": "rating",
					"rating": req.rating,
				},
				score_name="user-rating",
			)
		)
	if req.score is None and req.rating is None and comment:
		sent_results.append(
			telemetry.submit_feedback(
				trace_id=req.trace_id,
				score=None,
				comment=comment,
				metadata={
					"conversation_id": req.conversation_id,
					"message_id": req.message_id,
					"feedback_type": "comment",
				},
				score_name="user-comment",
			)
		)

	return {"status": "ok", "sent_to_langfuse": any(sent_results)}


@app.get("/api/seatmap", response_model=SeatMapResponse)
async def seatmap_endpoint(conversation_id: str):
	"""Return a data-driven seat map for the current conversation's flight."""
	state = conversation_store.get(conversation_id)
	if state is None:
		raise HTTPException(status_code=404, detail="Conversation not found")

	ctx = state.get("context")
	flight_number = getattr(ctx, "flight_number", None) if ctx is not None else None
	if not flight_number and isinstance(ctx, dict):
		flight_number = ctx.get("flight_number")
	if not flight_number:
		raise HTTPException(status_code=400, detail="No flight number available in conversation context")

	seat_layout = get_seats_by_flight(str(flight_number))
	if not seat_layout:
		raise HTTPException(status_code=404, detail=f"Seat map not available for flight {flight_number}")

	reserved = seat_assignment_store.occupied_seats(flight_number=str(flight_number))

	def _seat_sort_key(seat: str):
		row_str = "".join(ch for ch in seat if ch.isdigit())
		letter = "".join(ch for ch in seat if ch.isalpha())
		try:
			row = int(row_str) if row_str else 0
		except Exception:
			row = 0
		return (row, letter)

	sections: Dict[str, SeatMapSection] = {}
	for cabin in ("business", "economy"):
		cabin_data = seat_layout.get(cabin, {}) if isinstance(seat_layout, dict) else {}
		base_occupied = set(cabin_data.get("occupied", []) or [])
		all_occupied = sorted(base_occupied | reserved, key=_seat_sort_key)
		sections[cabin] = SeatMapSection(
			rows=cabin_data.get("rows", []) or [],
			seats_per_row=cabin_data.get("seats_per_row", []) or [],
			occupied=all_occupied,
			exit_rows=cabin_data.get("exit_rows", []) or [],
			premium=cabin_data.get("premium", []) or [],
		)

	current_seat = getattr(ctx, "seat_number", None) if ctx is not None else None
	if not current_seat and isinstance(ctx, dict):
		current_seat = ctx.get("seat_number")

	return SeatMapResponse(
		conversation_id=conversation_id,
		flight_number=str(flight_number),
		aircraft=seat_layout.get("aircraft") if isinstance(seat_layout, dict) else None,
		sections=sections,
		current_seat=current_seat,
	)


dist = files("agents_demo").joinpath("ui").joinpath("out")

app.mount("/", StaticFiles(directory=str(dist), html=True), name="web")
