from importlib.resources import files
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from uuid import uuid4
import time
import logging

from starlette.staticfiles import StaticFiles

# Import agents and context creation from main_qwen (SUPPORT QWEN MODEL)
from .main_qwen import (
	triage_agent,
	faq_agent,
	seat_booking_agent,
	flight_status_agent,
	cancellation_agent,
	create_initial_context,
	AirlineAgentContext,
	food_service_agent,
)
from .main_qwen import OpenAIModel as bOpenAIModel  # True: use OpenAI model; False: use Qwen model
from .main_qwen import myRunConfig
from .storage import JsonConversationStore
from .telemetry import Telemetry


"""
from main import (
    triage_agent,
    faq_agent,
    seat_booking_agent,
    flight_status_agent,
    cancellation_agent,
    create_initial_context,
)
"""

from agents import (
	Runner,
	ItemHelpers,
	MessageOutputItem,
	HandoffOutputItem,
	ToolCallItem,
	ToolCallOutputItem,
	InputGuardrailTripwireTriggered,
	Handoff,
)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

#fastapi app instance
app = FastAPI()

# CORS configuration (adjust as needed for deployment)
app.add_middleware(
	CORSMiddleware,
		allow_origins=["*"], #dangous security setting for demo purpose only
	#allow_origins=["http://localhost:3000","http://localhost:3001","http://localhost:3002"],
	allow_credentials=True,
	allow_methods=["*"],
	allow_headers=["*"],
)


# =========================
# Models
# =========================

# From frontend request
class ChatRequest(BaseModel):
	conversation_id: Optional[str] = None
	message: str

# agent message response
class MessageResponse(BaseModel):
	id: str
	content: str
	agent: str
	trace_id: Optional[str] = None
	timestamp: float
	feedback: Optional[float] = None

# agent event log of workflow
class AgentEvent(BaseModel):
	id: str
	type: str
	agent: str
	content: str
	metadata: Optional[Dict[str, Any]] = None
	timestamp: Optional[float] = None

# guardrail check input/output
class GuardrailCheck(BaseModel):
	id: str
	name: str
	input: str
	reasoning: str
	passed: bool
	timestamp: float


class FeedbackRequest(BaseModel):
	conversation_id: str
	message_id: str
	trace_id: str
	score: float
	comment: Optional[str] = None

#****************************************************************************************************
# ===================================================================================================
# Response Model： sending response back to frontend app
# Add fields, such as trace id for getting user feedback from frontend, fastapi app sending trace id
# generated by tracing agent run with langfuse， to frontend for display message with trace ID. 
# Traces can be scored in frontend app if obersavation platform allows multiple accesses simultaneously. 
# Otherwise，they can be sent back along with feedback values to backend for computing scores.
# ===================================================================================================
#****************************************************************************************************
class ChatResponse(BaseModel):
	conversation_id: str
	current_agent: str
	messages: List[MessageResponse]
	events: List[AgentEvent]
	context: Dict[str, Any]
	agents: List[Dict[str, Any]]
	guardrails: List[GuardrailCheck] = Field(default_factory=list)
	trace_id: Optional[str] = None

#===================================================================================
# Persistent conversation store instance
#===================================================================================
data_dir = Path(__file__).resolve().parent / "data"
conversation_store = JsonConversationStore(
	data_dir / "conversations.json",
	context_loader=lambda payload: AirlineAgentContext(**payload),
)

#===================================================================================
# Telemetry for trace logging and feedback forwarding
#===================================================================================
telemetry = Telemetry(
	trace_log=data_dir / "traces.jsonl",
	feedback_log=data_dir / "feedback.jsonl",
)

# =========================
# Helpers
# =========================

def _get_agent_by_name(name: str):
	"""Return the agent object by name."""
	agents = {
		triage_agent.name: triage_agent,
		faq_agent.name: faq_agent,
		seat_booking_agent.name: seat_booking_agent,
		flight_status_agent.name: flight_status_agent,
		cancellation_agent.name: cancellation_agent,
		food_service_agent.name: food_service_agent,
	}
	return agents.get(name, triage_agent)

def _get_guardrail_name(g) -> str:
	"""Extract a friendly guardrail name."""
	name_attr = getattr(g, "name", None)
	if isinstance(name_attr, str) and name_attr:
		return name_attr
	guard_fn = getattr(g, "guardrail_function", None)
	if guard_fn is not None and hasattr(guard_fn, "__name__"):
		return guard_fn.__name__.replace("_", " ").title()
	fn_name = getattr(g, "__name__", None)
	if isinstance(fn_name, str) and fn_name:
		return fn_name.replace("_", " ").title()
	return str(g)

def _build_agents_list() -> List[Dict[str, Any]]:
	"""Build a list of all available agents and their metadata."""
	def make_agent_dict(agent):
		return {
			"name": agent.name,
			"description": getattr(agent, "handoff_description", ""),
			"handoffs": [getattr(h, "agent_name", getattr(h, "name", "")) for h in getattr(agent, "handoffs", [])],
			"tools": [getattr(t, "name", getattr(t, "__name__", "")) for t in getattr(agent, "tools", [])],
			"input_guardrails": [_get_guardrail_name(g) for g in getattr(agent, "input_guardrails", [])],
		}
	return [
		make_agent_dict(triage_agent),
		make_agent_dict(faq_agent),
		make_agent_dict(seat_booking_agent),
		make_agent_dict(flight_status_agent),
		make_agent_dict(cancellation_agent),
		make_agent_dict(food_service_agent),
	]

# =========================
# Main Chat Endpoint
# =========================7

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest):
	print(f"Received chat request: conversation_id={req.conversation_id}, message={req.message} ")
	trace_id = uuid4().hex
	now_ms = time.time() * 1000
	"""
	Main chat endpoint for agent orchestration.
	Handles conversation state, agent routing, and guardrail checks.
	"""
	# Initialize or retrieve conversation state
	existing_state = conversation_store.get(req.conversation_id) if req.conversation_id else None
	is_new = existing_state is None
	if is_new:
		conversation_id: str = uuid4().hex
		ctx = create_initial_context()   #flight booking context
		current_agent_name = triage_agent.name

		#========================================
		#     state for first time conversation
		#========================================
		state: Dict[str, Any] = {
			"input_items": [], #list of TResponseInputItem for Runner.run
			"context": ctx,   #flight booking context
			"current_agent": current_agent_name, #agent to start with
			"trace_history": [],
			"feedback": [],
		}
		if req.message.strip() == "":
			conversation_store.save(conversation_id, state)
			return ChatResponse(
				conversation_id=conversation_id,
				current_agent=current_agent_name,
				messages=[],
				events=[],
				context=ctx.model_dump(),
				agents=_build_agents_list(),
				guardrails=[],
				trace_id=trace_id,
			)
	else:
		conversation_id = req.conversation_id
		#===============================================
		#   retrieve state for conversation from store
		#===============================================
		if existing_state is None:
			raise HTTPException(status_code=404, detail="Conversation not found")
		state = existing_state

	#=============================================
	# prepare parameters for Runner
	#=============================================
	current_agent = _get_agent_by_name(state["current_agent"])  #pick this agent for running
	state["input_items"].append({"content": req.message, "role": "user"})   #input for runner.run
	old_context = state["context"].model_dump().copy() if hasattr(state["context"], "model_dump") else dict(state["context"])  #context for runner.run
	guardrail_checks: List[GuardrailCheck] = []

	try:
		result = None

		#===========================================================================================
		# check: https://openai.github.io/openai-agents-python/ref/run/#agents.run.Runner.run
		# run with input(list[TResponseInputItem] ) and context (flight booking context)
		#===========================================================================================
		if(bOpenAIModel): #zdjiang added for qwen3
			result = await Runner.run(current_agent, state["input_items"], context=state["context"])
		else:
			result = await Runner.run(current_agent, state["input_items"], context=state["context"], run_config=myRunConfig)

	except InputGuardrailTripwireTriggered as e: #gurdrail tripwire triggered
		failed = e.guardrail_result.guardrail
		gr_output = e.guardrail_result.output.output_info
		gr_reasoning = getattr(gr_output, "reasoning", "")
		gr_input = req.message
		gr_timestamp = time.time() * 1000
		for g in current_agent.input_guardrails:
			guardrail_checks.append(GuardrailCheck(
				id=uuid4().hex,
				name=_get_guardrail_name(g),
				input=gr_input,
				reasoning=(gr_reasoning if g == failed else ""),
				passed=(g != failed),
				timestamp=gr_timestamp,
			))
		refusal = "Sorry, I can only answer questions related to airline travel."
		state["input_items"].append({"role": "assistant", "content": refusal})  # record refusal in conversation history
		refusal_message = MessageResponse(
			id=uuid4().hex,
			content=refusal,
			agent=current_agent.name,
			trace_id=trace_id,
			timestamp=gr_timestamp,
		)
		conversation_store.save(conversation_id, state)
		telemetry.record_trace(
			trace_id=trace_id,
			conversation_id=conversation_id,
			agent=current_agent.name,
			user_message=req.message,
			assistant_messages=[refusal_message.model_dump()],
			guardrails=[gc.model_dump() for gc in guardrail_checks],
		)
		return ChatResponse(
			conversation_id=conversation_id,
			current_agent=current_agent.name,
			messages=[refusal_message],
			events=[],
			context=state["context"].model_dump() if hasattr(state["context"], "model_dump") else state["context"],
			agents=_build_agents_list(),
			guardrails=guardrail_checks,
			trace_id=trace_id,
		)
    
	# ===============================
	#  Process result items
	#================================
	messages: List[MessageResponse] = []  #agent messages to return
	events: List[AgentEvent] = []  #agent events to return
    
	#================================================================================
	# Process new items from the run result
	# check: https://openai.github.io/openai-agents-python/ref/result/
	# check: https://openai.github.io/openai-agents-python/ref/items/
	#================================================================================
	for item in result.new_items:
		if isinstance(item, MessageOutputItem):
			text = ItemHelpers.text_message_output(item)
			msg_ts = time.time() * 1000
			msg_id = uuid4().hex
			messages.append(
				MessageResponse(
					id=msg_id,
					content=text,
					agent=item.agent.name,
					trace_id=trace_id,
					timestamp=msg_ts,
				)
			)
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="message",
					agent=item.agent.name,
					content=text,
					timestamp=msg_ts,
				)
			)
        
		# Handle handoff output and agent switching
		elif isinstance(item, HandoffOutputItem):
			# Record the handoff event
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="handoff",
					agent=item.source_agent.name,
					content=f"{item.source_agent.name} -> {item.target_agent.name}",
					metadata={"source_agent": item.source_agent.name, "target_agent": item.target_agent.name},
					timestamp=time.time() * 1000,
				)
			)
			# If there is an on_handoff callback defined for this handoff, show it as a tool call
			from_agent = item.source_agent
			to_agent = item.target_agent
			# Find the Handoff object on the source agent matching the target
			ho = next(
				(	h for h in getattr(from_agent, "handoffs", [])
					if isinstance(h, Handoff) and getattr(h, "agent_name", None) == to_agent.name),
				None,
			)
			if ho:
				fn = ho.on_invoke_handoff
				fv = fn.__code__.co_freevars
				cl = fn.__closure__ or []
				if "on_handoff" in fv:
					idx = fv.index("on_handoff")
					if idx < len(cl) and cl[idx].cell_contents:
						cb = cl[idx].cell_contents
						cb_name = getattr(cb, "__name__", repr(cb))
						events.append(
							AgentEvent(
								id=uuid4().hex,
								type="tool_call",
								agent=to_agent.name,
								content=cb_name,
								timestamp=time.time() * 1000,
							)
						)
			#==========================================================
			# handoff target agent is the starting agent of next run
			current_agent = item.target_agent
			#==========================================================

		elif isinstance(item, ToolCallItem):
			tool_name = getattr(item.raw_item, "name", None)
			raw_args = getattr(item.raw_item, "arguments", None)
			tool_args: Any = raw_args
			if isinstance(raw_args, str):
				try:
					import json
					tool_args = json.loads(raw_args)
				except Exception:
					pass
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="tool_call",
					agent=item.agent.name,
					content=tool_name or "",
					metadata={"tool_args": tool_args},
					timestamp=time.time() * 1000,
				)
			)
            
			#================== important trick for frontend interaction ===================================
			# If the tool is display_seat_map, send a special message so the UI can render the seat selector.
			#===============================================================================================
			if tool_name == "display_seat_map":
				messages.append(
					MessageResponse(
						id=uuid4().hex,
						content="DISPLAY_SEAT_MAP",
						agent=item.agent.name,
						trace_id=trace_id,
						timestamp=time.time() * 1000,
					)
				)
		elif isinstance(item, ToolCallOutputItem):
			events.append(
				AgentEvent(
					id=uuid4().hex,
					type="tool_output",
					agent=item.agent.name,
					content=str(item.output),
					metadata={"tool_result": item.output},
					timestamp=time.time() * 1000,
				)
			)
    
	# Check for context updates
	new_context = state["context"].model_dump()
	changes = {k: new_context[k] for k in new_context if old_context.get(k) != new_context[k]}
	if changes:
		events.append(
			AgentEvent(
				id=uuid4().hex,
				type="context_update",
				agent=current_agent.name,
				content="",
				metadata={"changes": changes},
				timestamp=time.time() * 1000,
			)
		)
	#==================================================================================================
	# Save updated conversation state
	# https://openai.github.io/openai-agents-python/running_agents/#conversationschat-threads
	# https://openai.github.io/openai-agents-python/ref/result/#agents.result.RunResult.to_input_list
	state["input_items"] = result.to_input_list() #check above links for to_input_list method details
	state["current_agent"] = current_agent.name
	#==================================================================================================

	# Build guardrail results: mark failures (if any), and any others as passed
	final_guardrails: List[GuardrailCheck] = []
	for g in getattr(current_agent, "input_guardrails", []):
		name = _get_guardrail_name(g)
		failed = next((gc for gc in guardrail_checks if gc.name == name), None)
		if failed:
			final_guardrails.append(failed)
		else:
			final_guardrails.append(GuardrailCheck(
				id=uuid4().hex,
				name=name,
				input=req.message,
				reasoning="",
				passed=True,
				timestamp=time.time() * 1000,
			))

	state.setdefault("trace_history", []).append(
		{
			"trace_id": trace_id,
			"timestamp": now_ms,
			"agent": current_agent.name,
			"messages": [m.model_dump() for m in messages],
			"guardrails": [g.model_dump() for g in final_guardrails],
		}
	)
	conversation_store.save(conversation_id, state)

	telemetry.record_trace(
		trace_id=trace_id,
		conversation_id=conversation_id,
		agent=current_agent.name,
		user_message=req.message,
		assistant_messages=[m.model_dump() for m in messages],
		guardrails=[g.model_dump() for g in final_guardrails],
		metadata={"events": [e.model_dump() for e in events]},
	)

	#return response for frontend
	return ChatResponse(
		conversation_id=conversation_id,
		current_agent=current_agent.name,
		messages=messages,
		events=events,
		context=state["context"].model_dump(),
		agents=_build_agents_list(),
		guardrails=final_guardrails,
		trace_id=trace_id,
	)


@app.post("/api/feedback")
async def feedback_endpoint(req: FeedbackRequest):
	"""Collect user feedback from the UI and optionally forward to Langfuse."""
	if req.score < 0 or req.score > 1:
		raise HTTPException(status_code=400, detail="Score must be between 0 and 1")

	state = conversation_store.get(req.conversation_id)
	if state is None:
		raise HTTPException(status_code=404, detail="Conversation not found")

	entry = {
		"message_id": req.message_id,
		"trace_id": req.trace_id,
		"score": req.score,
		"comment": req.comment,
		"timestamp": time.time() * 1000,
	}
	state.setdefault("feedback", []).append(entry)
	conversation_store.save(req.conversation_id, state)

	sent_to_langfuse = telemetry.submit_feedback(
		trace_id=req.trace_id,
		score=req.score,
		comment=req.comment,
		metadata={"conversation_id": req.conversation_id, "message_id": req.message_id},
	)

	return {"status": "ok", "sent_to_langfuse": sent_to_langfuse}


dist = files("agents_demo").joinpath("ui").joinpath("out")

app.mount("/", StaticFiles(directory=str(dist), html=True), name="web")
